CREATE OR REPLACE PROCEDURE insertLecture(
	sStudentId IN VARCHAR2, nYear IN NUMBER,
	nSemester IN NUMBER,	nDAY IN NUMBER,
	n_ST_H IN NUMBER,	n_ST_M IN NUMBER,
	n_ET_H IN NUMBER,	n_ET_M IN NUMBER,
	nLOC IN VARCHAR2
)
IS


BEGIN

END;